### PR TITLE
bugfix: cannot reuse actor when run_test.py again

### PR DESCRIPTION
**Pull request by daisukes**

### CODE REVIEW

**Comment by muratams** [comment]
Confirmed that the issue can be solved by the change.

But I found another minor issue that changing the name of a person from ID (e.g. 0) to name (e.g. actor0) causes people_vis.py node to crash.

The change of pedestrian plugin is
https://github.com/CMU-cabot/cabot-navigation/commit/aa0c6789e80c2e69f5ceb3e59de97910d82ff906#diff-195d911a4828f18d8792650ec08066e35212a9ca45e4c0d96d4c5ceab8f43dabL305
```
- person.name = std::to_string(actor_id);
+ person.name = this->name;
```
but people_vis assumes person.name to be integer.
https://github.com/CMU-cabot/cabot-common/blob/00dd72b53c199e803bf1a38ed50feb301550ec1a/cabot_common/scripts/people_vis.py#L85
```
def init_marker(frame_id, marker, person, type_, r=0.0, g=0.0, b=0.0, a=1.0):
    ...
    marker.id = int(person.name)
```

One potential solution is extracting digit from person.name then convert it to int.

**Comment by muratams** [comment]
Created a Pull Request to fix the side effect in [cabot-common](https://github.com/CMU-cabot/cabot-common).

**Comment by daisukes** [comment]
Oh, thanks!
Merged the PR.

**Review by muratams — APPROVED** [review]
It was confirmed that the issue was solved by this change.

**Pull request merged**
