### PR TITLE
Add functions to improve test and evaluation for cabot_navigation2

### PR DESCRIPTION
**Pull request by muratams**
Summary of changes
- update pedestrian modules to extend pedestrian behavior in test cases
- add Evaluator class to compute metrics for evaluating navigation
- update pedestrian_plugin to publish /robot_states and /human_states messages for the evaluator

### CODE REVIEW

**Comment by muratams** [comment]
Implementation of evaluation metrics and pedestrian modules is still in progress but I created this pull request to ensure the direction of implementation is ok and avoid conflicts in the future.

**Comment by daisukes** [comment]
This is a good start!

- publish robot and pedestrian state from the plugin
- test will call set_evaluation_parameter and start_evaluation to get metrics in a test
- evaluator subscribers to the state and calculate specified metrics

Could you please add README stating what kind of metrics can be used.

Btw, how should we output the result? How should we check if metrics meet requirements? Just compare the value in each test or provide a higher-level abstraction?

**Comment by muratams** [comment]
I need some more work to refine README and this PR.

> Btw, how should we output the result? How should we check if metrics meet requirements? Just compare the value in each test or provide a higher-level abstraction?

For testing (mainly for regression testing) purpose, it is sufficient to add assertions to each test case, for example
```
# fails if the robot moves too slow
tester.check_topic_error(
    action="check total_time ",
    topic="/metric",
    topic_type="pedestrian_plugin_msgs/msg/Metric",
    condition="msg.name=='total_time' and 30.0<=msg.value"
)
```
It would be better to add shorthand or dedicated functions for this purpose.

For comparison between test runs (e.g. comparing the effect of changes on navigation), it is necessary to add a feature to collect evaluation metrics for all test cases and output them with a test run identifier in some format.

**Comment by muratams** [comment]
Updated cabot_navigtion2/test/README.md and added a pointer to evaluation_metrics module that defines callable metric functions.

**Review by dsato80 — APPROVED** [review]
LGTM

**Pull request merged**
